# Generated by Django 4.2.7 on 2023-11-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя автора'),
        ),
    ]
