# Generated by Django 4.1.3 on 2023-11-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_delete_post_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
