# Generated by Django 4.1.3 on 2023-11-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_contactus_options_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
